<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <artifactId>l2fprod-common-all</artifactId>
    <groupId>com.l2fprod.common</groupId>
    <version>7.4-SNAPSHOT</version>
    <relativePath>../../pom.xml</relativePath>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>l2fprod-common-all-jar</artifactId>
  <packaging>jar</packaging>
  <name>l2fprod-common-all (uber-jar)</name>

  <dependencies>
    <dependency>
      <groupId>com.l2fprod.common</groupId>
      <artifactId>l2fprod-common-buttonbar</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.l2fprod.common</groupId>
      <artifactId>l2fprod-common-directorychooser</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.l2fprod.common</groupId>
      <artifactId>l2fprod-common-fontchooser</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.l2fprod.common</groupId>
      <artifactId>l2fprod-common-outlookbar</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.l2fprod.common</groupId>
      <artifactId>l2fprod-common-shared</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.l2fprod.common</groupId>
      <artifactId>l2fprod-common-sheet</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.l2fprod.common</groupId>
      <artifactId>l2fprod-common-tasks</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.l2fprod.common</groupId>
      <artifactId>l2fprod-common-totd</artifactId>
      <version>${project.version}</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-shade-plugin</artifactId>
        <version>3.4.1</version>
        <executions>
          <execution>
            <phase>package</phase>
            <goals>
              <goal>shade</goal>
            </goals>
            <configuration>
              <createDependencyReducedPom>true</createDependencyReducedPom>
              <shadedArtifactAttached>false</shadedArtifactAttached>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <version>${maven.assembly.plugin.version}</version>
        <executions>
          <execution>
            <id>make-aggregate-sources</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
            <configuration>
              <descriptors>
                <descriptor>assembly-sources.xml</descriptor>
              </descriptors>
              <runOnlyAtExecutionRoot>false</runOnlyAtExecutionRoot>
              <appendAssemblyId>true</appendAssemblyId>
              <attach>true</attach>
              <formats>
                <format>jar</format>
              </formats>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
